### ISSUE TITLE
Suggestion about hosting this project

### ISSUE THREAD

**Issue by miaochiahao** [KathanP19/HowToHunt#115]
I wanna suggest that this awesome project could be hosted with [mdwiki](http://dynalon.github.io/mdwiki/#!tutorials/github.md), and then we'll get a readable web wiki page totally powered by the front end.
It's much easier and friendly to read or negavite.

**Comment by KathanP19** [comment]
It might get hard to manage, and yet there is a lot of formatting needed to the repo, so right now it might be not possible but in the future, sure we will consider, Thank you for the suggestion 👍
