### ISSUE TITLE
HTML injection on password reset link

### ISSUE THREAD

**Issue by Pratish58** [KathanP19/HowToHunt#132]
Hi, 
I find this github page super helpful. I have a bug idea and would like to contribute. Thanks! 
[Html-injection.txt](https://github.com/KathanP19/HowToHunt/files/6134524/Html-injection.txt)

**Comment by KathanP19** [comment]
Thanks for contributing @Pratish58, will be looking for more in future. 💯 
@all-contributors please add @Pratish58  for tutorial
