### ISSUE TITLE
Web Application Pentest Checklist

### ISSUE THREAD

**Issue by e11i0t4lders0n** [KathanP19/HowToHunt#170]
[Web_Application_Penetration_Testing_Checklist_by_Tushar_Verma.pdf](https://github.com/KathanP19/HowToHunt/files/6765473/Web_Application_Penetration_Testing_Checklist_by_Tushar_Verma.pdf)

**Comment by KathanP19** [comment]
Nice checklist, man. I'll add it and look forward to seeing more contributions. 😄
